# Generated by Django 5.2.17 on 2026-09-30 00:21

import accounts.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecredential',
            name='access_token',
            field=accounts.fields.EncryptedTextField(blank=True, db_default='', default='', help_text='The last access token, valid for about an hour.'),
        ),
        migrations.AddField(
            model_name='googlecredential',
            name='access_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlecredential',
            name='drive_connected_at',
            field=models.DateTimeField(blank=True, help_text="When the user connected Google Drive. Empty while it isn't connected.", null=True, verbose_name='Google Drive connected at'),
        ),
        migrations.AddField(
            model_name='googlecredential',
            name='granted_scopes',
            field=models.TextField(blank=True, db_default='', default='', help_text='The scopes Google last reported, separated by spaces.'),
        ),
        migrations.AddField(
            model_name='googlecredential',
            name='refresh_token',
            field=accounts.fields.EncryptedTextField(blank=True, db_default='', default='', help_text="Google's refresh token, which gets new access tokens."),
        ),
    ]
