# Generated by Django 5.2.17 on 2026-09-24 04:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(help_text='Such as USPS.', max_length=100)),
                ('service', models.CharField(help_text='Such as Priority.', max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Three-letter ISO 4217 code, such as USD.', max_length=3)),
                ('delivery_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text="The order's ID in the Sheet.", max_length=100, verbose_name='external ID')),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_street1', models.CharField(max_length=255, verbose_name='recipient street 1')),
                ('recipient_street2', models.CharField(blank=True, max_length=255, verbose_name='recipient street 2')),
                ('recipient_city', models.CharField(max_length=100)),
                ('recipient_state', models.CharField(blank=True, max_length=100)),
                ('recipient_postal_code', models.CharField(blank=True, max_length=20)),
                ('recipient_country', models.CharField(help_text='Two-letter ISO 3166-1 code, such as US.', max_length=2)),
                ('weight_oz', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='weight (oz)')),
                ('length_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='length (in)')),
                ('width_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='width (in)')),
                ('height_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='height (in)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('rated', 'Rated'), ('selected', 'Selected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnomalyFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning')], max_length=20)),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_flags', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easypost_id', models.CharField(blank=True, help_text="EasyPost's shipment ID (shp_…). Blank until rates are fetched.", max_length=100, verbose_name='EasyPost ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.order')),
                ('selected_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.rate')),
            ],
        ),
        migrations.AddField(
            model_name='rate',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='orders.shipment'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('user', 'external_id'), name='orders_order_external_id_unique_per_user', violation_error_message='You already have an order with this ID.'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('external_id', ''), _negated=True), name='orders_order_external_id_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'rated', 'selected'])), name='orders_order_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('recipient_country__regex', '^[A-Z]{2}$')), name='orders_order_recipient_country_valid', violation_error_message='Enter the country as a two-letter code in capitals, such as US.'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('weight_oz__gt', 0)), name='orders_order_weight_oz_positive', violation_error_message='The weight must be greater than 0.'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('length_in__gt', 0)), name='orders_order_length_in_positive', violation_error_message='The length must be greater than 0.'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('width_in__gt', 0)), name='orders_order_width_in_positive', violation_error_message='The width must be greater than 0.'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('height_in__gt', 0)), name='orders_order_height_in_positive', violation_error_message='The height must be greater than 0.'),
        ),
        migrations.AddConstraint(
            model_name='anomalyflag',
            constraint=models.CheckConstraint(condition=models.Q(('severity__in', ['info', 'warning'])), name='orders_anomalyflag_severity_valid'),
        ),
        migrations.AddConstraint(
            model_name='rate',
            constraint=models.CheckConstraint(condition=models.Q(('cost__gte', 0)), name='orders_rate_cost_not_negative', violation_error_message="The cost can't be negative."),
        ),
        migrations.AddConstraint(
            model_name='rate',
            constraint=models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='orders_rate_currency_valid', violation_error_message='Enter the currency as a three-letter code in capitals, such as USD.'),
        ),
    ]
